# Generated by Django 3.0.4 on 2020-05-11 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('company_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('currency_id', models.IntegerField(primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=20)),
                ('currency_mark', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('vendor_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=50)),
                ('post_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('representative', models.CharField(max_length=20, null=True)),
                ('payment_account', models.CharField(max_length=100)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Companies')),
            ],
        ),
        migrations.CreateModel(
            name='BillsHeader',
            fields=[
                ('invoice_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('limit', models.DateField(auto_now_add=True)),
                ('terms', models.IntegerField(default=0)),
                ('payed_flag', models.IntegerField(default=0)),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Currencies')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.Departments')),
            ],
        ),
        migrations.CreateModel(
            name='BillsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=20)),
                ('invoice_detail_number', models.IntegerField()),
                ('part_number', models.CharField(max_length=50)),
                ('part_name', models.CharField(max_length=50)),
                ('unit_price', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
            options={
                'unique_together': {('invoice_id', 'invoice_detail_number')},
            },
        ),
    ]
