# Generated by Django 3.0.4 on 2020-05-14 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('delete_flag', models.IntegerField(choices=[(0, '未削除'), (1, '削除済')], default=0, null=True)),
                ('create_user', models.CharField(editable=False, max_length=20, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_user', models.CharField(editable=False, max_length=20, null=True)),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('company_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('delete_flag', models.IntegerField(choices=[(0, '未削除'), (1, '削除済')], default=0, null=True)),
                ('create_user', models.CharField(editable=False, max_length=20, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_user', models.CharField(editable=False, max_length=20, null=True)),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('currency_id', models.IntegerField(primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=20)),
                ('currency_mark', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('delete_flag', models.IntegerField(choices=[(0, '未削除'), (1, '削除済')], default=0, null=True)),
                ('create_user', models.CharField(editable=False, max_length=20, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_user', models.CharField(editable=False, max_length=20, null=True)),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('vendor_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('department_name', models.CharField(blank=True, default='', max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('post_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('representative', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_account', models.CharField(blank=True, max_length=100, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bills_Header',
            fields=[
                ('delete_flag', models.IntegerField(choices=[(0, '未削除'), (1, '削除済')], default=0, null=True)),
                ('create_user', models.CharField(editable=False, max_length=20, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_user', models.CharField(editable=False, max_length=20, null=True)),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50)),
                ('publish_date', models.DateField()),
                ('limit_date', models.DateField()),
                ('terms', models.IntegerField(choices=[(0, '振込'), (1, '引落')], default=0)),
                ('payed_flag', models.IntegerField(choices=[(0, '未払い'), (1, '支払済')], default=0)),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Currency')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.Department')),
            ],
            options={
                'ordering': ['limit_date', 'publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Bills_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_flag', models.IntegerField(choices=[(0, '未削除'), (1, '削除済')], default=0, null=True)),
                ('create_user', models.CharField(editable=False, max_length=20, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_user', models.CharField(editable=False, max_length=20, null=True)),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('invoice_detail_number', models.IntegerField()),
                ('part_number', models.CharField(max_length=50)),
                ('part_name', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('quantity', models.IntegerField()),
                ('product', models.DecimalField(decimal_places=5, default=0, editable=False, max_digits=20)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header', to='payment.Bills_Header')),
            ],
            options={
                'ordering': ['invoice_detail_number'],
                'unique_together': {('invoice_id', 'invoice_detail_number')},
            },
        ),
    ]
