# Generated by Django 3.0.4 on 2020-05-12 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('delete_flag', models.IntegerField(default=0, null=True)),
                ('create_user', models.CharField(editable=False, max_length=20, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_user', models.CharField(editable=False, max_length=20, null=True)),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('company_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('delete_flag', models.IntegerField(default=0, null=True)),
                ('create_user', models.CharField(editable=False, max_length=20, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_user', models.CharField(editable=False, max_length=20, null=True)),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('currency_id', models.IntegerField(primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=20)),
                ('currency_mark', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('delete_flag', models.IntegerField(default=0, null=True)),
                ('create_user', models.CharField(editable=False, max_length=20, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_user', models.CharField(editable=False, max_length=20, null=True)),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('vendor_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=50)),
                ('post_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('representative', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_account', models.CharField(blank=True, max_length=100, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bills_Header',
            fields=[
                ('delete_flag', models.IntegerField(default=0, null=True)),
                ('create_user', models.CharField(editable=False, max_length=20, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_user', models.CharField(editable=False, max_length=20, null=True)),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('limit', models.DateField(auto_now_add=True)),
                ('terms', models.IntegerField(choices=[(0, '振込'), (1, '引落')], default=0)),
                ('payed_flag', models.IntegerField(choices=[(0, 'payed'), (1, 'not yet')], default=0)),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Currency')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.Department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bills_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_flag', models.IntegerField(default=0, null=True)),
                ('create_user', models.CharField(editable=False, max_length=20, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_user', models.CharField(editable=False, max_length=20, null=True)),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('invoice_detail_number', models.IntegerField()),
                ('part_number', models.CharField(max_length=50)),
                ('part_name', models.CharField(max_length=50)),
                ('unit_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Bills_Header')),
            ],
            options={
                'unique_together': {('invoice_id', 'invoice_detail_number')},
            },
        ),
    ]
