# Generated by Django 3.0.4 on 2020-05-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills_header',
            name='payed_flag',
            field=models.IntegerField(choices=[(0, '支払済'), (1, '未払')], default=0),
        ),
    ]
