# Generated by Django 3.0.4 on 2020-05-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillsDetail',
            new_name='Bills_Detail',
        ),
        migrations.RenameModel(
            old_name='BillsHeader',
            new_name='Bills_Header',
        ),
    ]
