# Generated by Django 3.0.4 on 2020-05-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200512_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills_header',
            name='payed_flag',
            field=models.IntegerField(choices=[(0, '未払い'), (1, '支払済')], default=0),
        ),
    ]
