# Generated by Django 3.0.4 on 2020-05-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200511_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills_detail',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bills_detail',
            name='create_user',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bills_detail',
            name='delete_flag',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='bills_detail',
            name='update_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='bills_detail',
            name='update_user',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bills_header',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bills_header',
            name='create_user',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bills_header',
            name='delete_flag',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='bills_header',
            name='update_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='bills_header',
            name='update_user',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='create_user',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='delete_flag',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='update_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='update_user',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='currencies',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='currencies',
            name='create_user',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='currencies',
            name='delete_flag',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='currencies',
            name='update_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='currencies',
            name='update_user',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='create_user',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='delete_flag',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='update_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='update_user',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
