# Generated by Django 3.0.4 on 2020-05-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20200512_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills_detail',
            name='delete_flag',
            field=models.IntegerField(choices=[(0, '未削除'), (1, '削除済')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bills_header',
            name='delete_flag',
            field=models.IntegerField(choices=[(0, '未削除'), (1, '削除済')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='delete_flag',
            field=models.IntegerField(choices=[(0, '未削除'), (1, '削除済')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='delete_flag',
            field=models.IntegerField(choices=[(0, '未削除'), (1, '削除済')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='delete_flag',
            field=models.IntegerField(choices=[(0, '未削除'), (1, '削除済')], default=0, null=True),
        ),
    ]
