# Generated by Django 3.0.4 on 2020-05-11 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200511_2310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companies',
            new_name='Company',
        ),
        migrations.RenameModel(
            old_name='Currencies',
            new_name='Currency',
        ),
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
    ]
