# Generated by Django 3.0.4 on 2020-05-12 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200512_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bills_header',
            old_name='limit',
            new_name='limit_date',
        ),
    ]
