# Generated by Django 3.0.4 on 2020-05-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20200512_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills_header',
            name='limit_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bills_header',
            name='publish_date',
            field=models.DateField(),
        ),
    ]
