# Generated by Django 3.0.4 on 2020-05-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20200512_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills_detail',
            name='product',
            field=models.FloatField(default=0),
        ),
    ]
