# Generated by Django 3.0.4 on 2020-05-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_bills_detail_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills_detail',
            name='product',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='bills_detail',
            name='unit_price',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
