# Generated by Django 3.0.4 on 2020-05-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20200513_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills_detail',
            name='product',
            field=models.DecimalField(decimal_places=5, default=0, editable=False, max_digits=20),
        ),
    ]
