# Generated by Django 3.0.4 on 2020-05-13 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20200513_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bills_detail',
            options={'ordering': ['invoice_detail_number']},
        ),
        migrations.AlterModelOptions(
            name='bills_header',
            options={'ordering': ['limit_date', 'publish_date']},
        ),
        migrations.AlterField(
            model_name='bills_detail',
            name='invoice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header', to='payment.Bills_Header'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
